create database Project;
use Project;
create table Hr_Data (Employee_ID int,	
				MonthlyIncome int,	
                MonthlyRate	int,
                NumCompaniesWorked	int,
                Over18	Varchar (250),
                OverTime	Varchar (250),
                PercentSalaryHike	int,
                PerformanceRating	int,
                RelationshipSatisfaction int,
                StandardHours	int,
                StockOptionLevel	int,
                TotalWorkingYears	int,
                TrainingTimesLastYear	int,
                WorkLifeBalance	int,
                YearsAtCompany	int,
                YearsInCurrentRole	int,
                YearsSinceLastPromotion	int,
                YearsWithCurrManager	int,
                Age	int,
                Attrition	Varchar (250),
                BusinessTravel	varchar (250),
                DailyRate	int,
                Department	Varchar (250),
                DistanceFromHome	int,
                Education	Varchar (250),
                EducationField	Varchar (250),
                EmployeeCount	int,
                Employee_ID2	int,
                EnvironmentSatisfaction	int,
                Gender	varchar (250),
                HourlyRate	int,
                JobInvolvement	int,
                JobLevel	int,
                JobRole	varchar (250),
                JobSatisfaction	int,
                MaritalStatus Varchar (250));
select * from Hr_data;
drop table hr_data;